name: cypress-tests
on:
  push:
    branches:
      - master
      
jobs:
  actions-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Setup NodeJS v14
        uses: actions/setup-node@v2
        with:
          node-version: 14.18.1

      - name: Install Dependencies
        run: npm ci

      - name: Run Cypress - E2E Tests
        run: npm run cy:e2e:run

      - name: Run Cypress - Integration Tests
        run: npm run cy:integration:run
